apiVersion: apps/v1
kind: Deployment
metadata:
  name: wechat-mp-server
  namespace: default
  labels:
    app: wechat-mp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wechat-mp-server
  template:
    metadata:
      labels:
        app: wechat-mp-server
    spec:
      containers:
        - name: wechat-mp-server
          image: {{.image_repo.Value}}:{{.image_tag}}
          ports:
            - containerPort: {{.service_port.Value}}
              protocol: TCP
          imagePullPolicy: Always
          env:
            - name: SENTRY.DSN
              value: {{.sentry_dsn.Value}}
            - name: WECHAT.APPID
              value: {{.wechat_appid.Value}}
            - name: WECHAT.APPSECRET
              value: {{.wechat_appsecret.Value}}
            - name: WECHAT.TOKEN
              value: {{.wechat_token.Value}}
            - name: WECHAT.ENCODINGAESKEY
              value: {{.wechat_encodingaeskey.Value}}
            - name: HTTPENGINE.PORT
              value: {{.service_port.Value}}
      restartPolicy: Always