name: Go Build
on:
  push:
    branches:
      - master
env:
  CI_BIN: wechat-mp-server
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: load Go 1.18 env
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          GOOS=linux GPARCH=amd64 go build -o ${{ env.CI_BIN }} -ldflags "-X 'wechat-mp-server/config.Version=$(git show -s --format=%h)'"

#      到这里编译就已经结束了 请自己根据自己的需要编辑ci文件